_BASE_: maskformer2_R50_bs16_90k.yaml
MODEL:
  WEIGHTS: "pretrain/coco-mask2former-r101-50epoch-model_final_eba159.pkl" #"R-101.pkl"
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "BN" #"SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used

SOLVER:
  IMS_PER_BATCH: 6
  CHECKPOINT_PERIOD: 40000
  WARMUP_FACTOR: 0.5
  WARMUP_ITERS: 1500
  BASE_LR: 0.0001
  MAX_ITER: 40000


INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 1024) for x in range(5, 10)]"] #(5, 21)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096 # max 是 2048的话，min_size_train里面尺寸不起作用，因为会超过2028，再被scale到2048. 所以原来设置是4096 
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE:  (512, 1024)  # 1024*1024 will cause shape mismatch in UDA


DATASETS:
  # TRAIN: ('kitti360_instance_seg_train',) 
  TRAIN: ('synthia_instance_seg_traine_val_cityscapes',) 

  TEST: ("cityscapes_fine_instance_seg_val",)

TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "./output/a_kitti_r101/kitti"