CUDA_VISIBLE_DEVICES=0 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_90k_kitti.yaml  DATASETS.TRAIN "('synscapes_human_cycle_instance_seg_train_eval_kitti360',)"   OUTPUT_DIR ./output/a_category_4UDA_swinL/kitti_synscapes_human_cycle >> ./output/a_category_4UDA_swinL/kitti_synscapes_human_cycle.txt &
CUDA_VISIBLE_DEVICES=1 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_90k_kitti.yaml  DATASETS.TRAIN "('synscapes_vehicle_instance_seg_train_eval_kitti360',)"   OUTPUT_DIR ./output/a_category_4UDA_swinL/kitti_synscapes_vehicle >> ./output/a_category_4UDA_swinL/kitti_synscapes_vehicle.txt  &

CUDA_VISIBLE_DEVICES=2 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_90k_kitti.yaml  DATASETS.TRAIN "('synthia_human_cycle_instance_seg_train_eval_kitti360',)"   OUTPUT_DIR ./output/a_category_4UDA_swinL/kitti_synthia_human_cycle >> ./output/a_category_4UDA_swinL/kitti_synthia_human_cycle.txt &
CUDA_VISIBLE_DEVICES=3 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_90k_kitti.yaml  DATASETS.TRAIN "('synthia_vehicle_instance_seg_train_eval_kitti360',)"   OUTPUT_DIR ./output/a_category_4UDA_swinL/kitti_synthia_vehicle >> ./output/a_category_4UDA_swinL/kitti_synthia_vehicle.txt  &
####################################################################################################################################################################
CUDA_VISIBLE_DEVICES=1 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/maskformer2_R101_bs16_90k-kitti.yaml  DATASETS.TRAIN "('synscapes_human_cycle_instance_seg_train_eval_kitti360',)"   OUTPUT_DIR ./output/a_category_4UDA_resnet101/kitti_synscapes_human_cycle >> ./output/a_category_4UDA_resnet101/kitti_synscapes_human_cycle.txt &
CUDA_VISIBLE_DEVICES=3 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/maskformer2_R101_bs16_90k-kitti.yaml  DATASETS.TRAIN "('synscapes_vehicle_instance_seg_train_eval_kitti360',)"   OUTPUT_DIR ./output/a_category_4UDA_resnet101/kitti_synscapes_vehicle >> ./output/a_category_4UDA_resnet101/kitti_synscapes_vehicle.txt  &

CUDA_VISIBLE_DEVICES=4 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/maskformer2_R101_bs16_90k-kitti.yaml  DATASETS.TRAIN "('synthia_human_cycle_instance_seg_train_eval_kitti360',)"   OUTPUT_DIR ./output/a_category_4UDA_resnet101/kitti_synthia_human_cycle >> ./output/a_category_4UDA_resnet101/kitti_synthia_human_cycle.txt &
CUDA_VISIBLE_DEVICES=4 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/maskformer2_R101_bs16_90k-kitti.yaml  DATASETS.TRAIN "('synthia_vehicle_instance_seg_train_eval_kitti360',)"   OUTPUT_DIR ./output/a_category_4UDA_resnet101/kitti_synthia_vehicle >> ./output/a_category_4UDA_resnet101/kitti_synthia_vehicle.txt 
