CUDA_VISIBLE_DEVICES=0 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_90k_uda.yaml  MODEL.WEIGHTS "./output/a_category_4UDA_swinL/cs_urbansyn_human_cycle/model_final.pth"      DATASETS.TRAIN "('uda_urbansyn_syn_real_human_cycle_instance_seg_train_eval_cityscapes',)"   OUTPUT_DIR ./output/a_category_4UDA_swinL/uda_cs_urbansyn_human_cycle_LAB_filter3000 >> ./output/a_category_4UDA_swinL/uda_cs_urbansyn_human_cycle_LAB_filter3000.txt &
CUDA_VISIBLE_DEVICES=1 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_90k_uda.yaml  MODEL.WEIGHTS "./output/a_category_4UDA_swinL/cs_urbansyn_vehicle/model_final.pth"      DATASETS.TRAIN "('uda_urbansyn_syn_real_vehicle_instance_seg_train_eval_cityscapes',)"   OUTPUT_DIR ./output/a_category_4UDA_swinL/uda_cs_urbansyn_vehicle_LAB_filter3000 >> ./output/a_category_4UDA_swinL/uda_cs_urbansyn_vehicle_LAB_filter3000.txt &

CUDA_VISIBLE_DEVICES=2 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_90k_uda.yaml  MODEL.WEIGHTS "./output/a_category_4UDA_swinL/cs4best_synscapes_human_cycle/model_final.pth"  DATASETS.TRAIN "('uda_synscapes_syn_real_human_cycle_instance_seg_train_eval_cityscapes',)"   OUTPUT_DIR ./output/a_category_4UDA_swinL/uda_cs_synscapes_human_cycle_LAB_filter3000 >> ./output/a_category_4UDA_swinL/uda_cs_synscapes_human_cycle_LAB_filter3000.txt &
CUDA_VISIBLE_DEVICES=3 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_90k_uda.yaml  MODEL.WEIGHTS "./output/a_category_4UDA_swinL/cs4best_synscapes_vehicle/model_final.pth"    DATASETS.TRAIN "('uda_synscapes_syn_real_vehicle_instance_seg_train_eval_cityscapes',)"   OUTPUT_DIR ./output/a_category_4UDA_swinL/uda_cs_synscapes_vehicle_LAB_filter3000 >> ./output/a_category_4UDA_swinL/uda_cs_synscapes_vehicle_LAB_filter3000.txt &

CUDA_VISIBLE_DEVICES=4 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_90k_uda.yaml  MODEL.WEIGHTS "./output/a_category_4UDA_swinL/cs4best_synthia_human_cycle/model_final.pth" INPUT.MIN_SIZE_TRAIN  "[614, 716, 819, 921, 1024]"  DATASETS.TRAIN "('uda_synthia_syn_real_human_cycle_instance_seg_train_eval_cityscapes',)"   OUTPUT_DIR ./output/a_category_4UDA_swinL/uda_cs_synthia_human_cycle_LAB_filter3000 >> ./output/a_category_4UDA_swinL/uda_cs_synthia_human_cycle_LAB_filter3000.txt &
CUDA_VISIBLE_DEVICES=5 python train_net.py --num-gpus 1 --dist-url   tcp://127.0.0.1:50160 --config-file configs/cityscapes/instance-segmentation/swin/maskformer2_swin_large_IN21k_384_bs16_90k_uda.yaml  MODEL.WEIGHTS "./output/a_category_4UDA_swinL/cs4best_synthia_vehicle/model_final.pth" INPUT.MIN_SIZE_TRAIN  "[614, 716, 819, 921, 1024]"   DATASETS.TRAIN "('uda_synthia_syn_real_vehicle_instance_seg_train_eval_cityscapes',)"   OUTPUT_DIR ./output/a_category_4UDA_swinL/uda_cs_synthia_vehicle_LAB_filter3000 >> ./output/a_category_4UDA_swinL/uda_cs_synthia_vehicle_LAB_filter3000.txt

